### ISSUE TITLE
New Lines are not respected in the problem field.

### ISSUE THREAD

**Issue by Snowy556** [bboisclair/PS-PAR-Form#8]
When entering a complex problem, that requires multiple lines of text, when generating the template they are all combined.

Expected Result:
The generated PAR form should have the same spacing as what was entered in the Problem field.
![Issue Description with proper spacing](https://github.com/bboisclair/PS-PAR-Form/assets/5615993/b70e3885-f389-43a4-a643-1ce2f3f338d5)

![Generated PAR form with incorrect spacing for problem statement](https://github.com/bboisclair/PS-PAR-Form/assets/5615993/8e24cdee-6df0-48a8-b1ba-24417d3c5b0b)

**Comment by bboisclair** [comment]
Resolved with v2.1 release
